---
apiVersion: v1
kind: Service
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: app-1
---
apiVersion: v1
kind: Service
metadata:
  name: app-2
  labels:
    app: app-2
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: app-2
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: app-3
  labels:
    app: app-3
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: app-3
  type: NodePort
---